/*
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeollllllIIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeIIoVEEEEEEEvlIiiiiiiIi!!!iIvOEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeI!!!!!IvEEEEoiiIIllllIIIIIli!ilvEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEElIIi!!!ii!!!lEEviIlllIi!!!!!!!IoIIIilOEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOoII!!!!!!!IllI!iLoIlIiiiIIII!!!!!loIIIilLEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeevllvoIIIlIIIIloollevli!ii!!!!!!!!!ILvlIIiIoeEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELLevllIIllIlollllllllllollllIIoolIIIlIIii!lLevlIIiIlloEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEELollIIIiiIIIIIIIloIIIIIIIIIIIllllollllovoollooooeeeelIIIiiIIleEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVvolI!!iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlllIlvvlloIiiiIlooIlllIIiiIlvEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEvooI!!!!iIIiIIIIlIIIIiIIIIIIIIIIIIIIIIli!!!IoliIol!!!!!!!!!!!iiiIllIiIlLEEEEEEEE
EEEEEEEEEEEEEEEEEELlIlli!!IIIIIIIIlvOliII!ilIIIIIIIIIIIIiIIIIii!ilolill!!!!!!!!!!!IollIooi!ILEEEEEEE
EEEEEEEEEEEEEEEEEoIloIIIIIIloIIIooIivvIIIIIIIIIllIIIlIIIIIIIIIIIIIIooIlo!!!!!!!ioeolIIilLvl!oEEEEEEE
EEEEEEEEEEEEEEEEeiIvIIIIIIleliloi!!!!IooolIIIIIIlolIlooolIIIIIIIIIIIveIleI!!!!IeeoIIIIIioEVlIVEEEEEE
EEEEEEEEEEEEEEELIIeIIIIIIlLeill!!!!!!!illovlIIIIIIovlIIoevoIIIIIIIIIIevioEI!!iOVevIIIIIioEEevEEEEEEE
EEEEEEEEEEEEEEEviLLiIIIIIvOvloiiiIIi!!!!iiovllllllllvvoIIovvlIIIIIIIioLolLVlIeEEVeIIIIiIeEVVEEEEEEEE
EEEEEEEEEEEEEEEvoEvIIIIIlLIIeI!!!iIIIi!!!!!iIiiiIlllIlooIIloeoiIIIIIioLvovEEVEEEEOliIiivEEEEEEEEEEEE
EEEEEEEEEEEEEEELLVVoiIIIvv!!iiIlllIIi!!!!!!!!!!!!!IoeveLLvliIvoIIIIIioevvOEEEEEEEeliilvEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEVVEoiiIol!IvLellvOVVLi!!!!!!!!!iLeLo!ieVVVOelllIIIilLvveEEEEEEEEviIoVEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEOEEvliillVvlLIivVOOVI!!!!!!!!!ii!OOoeVLvVeeLIlIIloooeeEEEEEEEEOeoEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEoooooi!LOveeoLL!!!!!!!!!!!!!ILeoolvLI!illIooIoIvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEVovLI!!!IlIIll!!!!!!!!!!!!!!!!iIIlIi!iooollllIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVlIeo!iiiIIIi!!!!!!!i!!!!!!!!!!iIiiIIIovIlllllIoEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEOlvELliIIIIII!!!!!iii!!!ii!!!!!iIIIIiilllolollEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEELOELeoIi!!!!!!!!!!Iii!iIi!!!!!!!!!iiIvovOvlIIloEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEviIovviiiii!!!!!!!!!!!!!!!!!iiIlEEEOLELlioeeLEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEOoiieVVEEOoIllovelllllolLVVVEEEEEEEEEEEeiIEEOEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEvIleVVEEEEVLOVOvvevvovOVOLOLLVEEEEEEELeeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEveEEEEVOLLLeevLLLeeeLOLLOLLLLOEEEEEVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLLeveeeLevveLLLLOLLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLLLLeveOvOOveeLLLOEVOLLOOLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOOLLOOOLOOOLOOLLLOEEVOLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOOLLLLevOLLLLLLLLOOeeLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLOLLLLLLLOOLLLLLLLLOvlvvvOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOOLLLLOLvLVLLLLLLLLLOoioLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELvOOLLLLLLLLOVOLLLLLLLLLOvIeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeolvevOLLLLOOOOLOOOLLOOLLeoLevEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvIlLlvoovIvvleelevoOvlLvlLvoveolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvlevoOeoeolOeleelLLovLooOeIvolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVelvolovloLvleeIveIIollleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOIiIIIIivEEEEVliIiii!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEv!!!!!!leEEEEe!!!!!!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEoiiii!oLEEEEOoIlllleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOLLOOEEEEEEOOOOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOLOEEEEEEEOLLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLVEEEEEEEVOLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOVEEEEEEEEVOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOVEEEEEEEEEEVVVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                賢い　可愛い　エリチカ Хорошо  保佑无BUG
                μ's は　大好き
                みんな　は　大好き
                LOVELIVE!  ラブライブ
*/


#include<cstdio>
#include<stack>
using namespace std;
typedef long long lovelive;

int to8(int n){
        int ans=0;
        while(n){
                ans*=10;
                ans+=n%8;
                n/=8;
        }
        return ans;
}

void Do(int n){
        stack<int> s;

        while(n){
                s.push(n%10>=4?(n%10>=9)?n%10+2:n%10+1:n%10);
                n/=10;
        }
        while(!s.empty()){
                printf("%d",s.top());
                s.pop();
        }

}
int main(){
        int n;
        scanf("%d",&n);
        printf("%d\n",to8(n));
        Do(to8(n));
        return 0;
}
