/*
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeollllllIIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeIIoVEEEEEEEvlIiiiiiiIi!!!iIvOEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeI!!!!!IvEEEEoiiIIllllIIIIIli!ilvEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEElIIi!!!ii!!!lEEviIlllIi!!!!!!!IoIIIilOEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOoII!!!!!!!IllI!iLoIlIiiiIIII!!!!!loIIIilLEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeevllvoIIIlIIIIloollevli!ii!!!!!!!!!ILvlIIiIoeEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELLevllIIllIlollllllllllollllIIoolIIIlIIii!lLevlIIiIlloEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEELollIIIiiIIIIIIIloIIIIIIIIIIIllllollllovoollooooeeeelIIIiiIIleEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVvolI!!iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlllIlvvlloIiiiIlooIlllIIiiIlvEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEvooI!!!!iIIiIIIIlIIIIiIIIIIIIIIIIIIIIIli!!!IoliIol!!!!!!!!!!!iiiIllIiIlLEEEEEEEE
EEEEEEEEEEEEEEEEEELlIlli!!IIIIIIIIlvOliII!ilIIIIIIIIIIIIiIIIIii!ilolill!!!!!!!!!!!IollIooi!ILEEEEEEE
EEEEEEEEEEEEEEEEEoIloIIIIIIloIIIooIivvIIIIIIIIIllIIIlIIIIIIIIIIIIIIooIlo!!!!!!!ioeolIIilLvl!oEEEEEEE
EEEEEEEEEEEEEEEEeiIvIIIIIIleliloi!!!!IooolIIIIIIlolIlooolIIIIIIIIIIIveIleI!!!!IeeoIIIIIioEVlIVEEEEEE
EEEEEEEEEEEEEEELIIeIIIIIIlLeill!!!!!!!illovlIIIIIIovlIIoevoIIIIIIIIIIevioEI!!iOVevIIIIIioEEevEEEEEEE
EEEEEEEEEEEEEEEviLLiIIIIIvOvloiiiIIi!!!!iiovllllllllvvoIIovvlIIIIIIIioLolLVlIeEEVeIIIIiIeEVVEEEEEEEE
EEEEEEEEEEEEEEEvoEvIIIIIlLIIeI!!!iIIIi!!!!!iIiiiIlllIlooIIloeoiIIIIIioLvovEEVEEEEOliIiivEEEEEEEEEEEE
EEEEEEEEEEEEEEELLVVoiIIIvv!!iiIlllIIi!!!!!!!!!!!!!IoeveLLvliIvoIIIIIioevvOEEEEEEEeliilvEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEVVEoiiIol!IvLellvOVVLi!!!!!!!!!iLeLo!ieVVVOelllIIIilLvveEEEEEEEEviIoVEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEOEEvliillVvlLIivVOOVI!!!!!!!!!ii!OOoeVLvVeeLIlIIloooeeEEEEEEEEOeoEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEoooooi!LOveeoLL!!!!!!!!!!!!!ILeoolvLI!illIooIoIvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEVovLI!!!IlIIll!!!!!!!!!!!!!!!!iIIlIi!iooollllIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVlIeo!iiiIIIi!!!!!!!i!!!!!!!!!!iIiiIIIovIlllllIoEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEOlvELliIIIIII!!!!!iii!!!ii!!!!!iIIIIiilllolollEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEELOELeoIi!!!!!!!!!!Iii!iIi!!!!!!!!!iiIvovOvlIIloEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEviIovviiiii!!!!!!!!!!!!!!!!!iiIlEEEOLELlioeeLEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEOoiieVVEEOoIllovelllllolLVVVEEEEEEEEEEEeiIEEOEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEvIleVVEEEEVLOVOvvevvovOVOLOLLVEEEEEEELeeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEveEEEEVOLLLeevLLLeeeLOLLOLLLLOEEEEEVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLLeveeeLevveLLLLOLLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLLLLeveOvOOveeLLLOEVOLLOOLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOOLLOOOLOOOLOOLLLOEEVOLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOOLLLLevOLLLLLLLLOOeeLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLOLLLLLLLOOLLLLLLLLOvlvvvOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOOLLLLOLvLVLLLLLLLLLOoioLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELvOOLLLLLLLLOVOLLLLLLLLLOvIeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeolvevOLLLLOOOOLOOOLLOOLLeoLevEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvIlLlvoovIvvleelevoOvlLvlLvoveolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvlevoOeoeolOeleelLLovLooOeIvolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVelvolovloLvleeIveIIollleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOIiIIIIivEEEEVliIiii!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEv!!!!!!leEEEEe!!!!!!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEoiiii!oLEEEEOoIlllleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOLLOOEEEEEEOOOOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOLOEEEEEEEOLLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLVEEEEEEEVOLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOVEEEEEEEEVOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOVEEEEEEEEEEVVVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                賢い　可愛い　エリチカ Хорошо  保佑无BUG
                μ's は　大好き
                みんな　は　大好き
*/

#include<stdio.h>


int main(){
    char c;
    int up;
    printf("touppper(1) or tolower(2)?");
    scanf("%c",&c);
    up=(c=='1'?1:0);
    while(1){
        scanf("%c",&c);
        if(c>='0'&&c<='9'){
            printf("Wrong!\ns");
            continue;
        }
        if(up==1){
            if(c>='a'&&c<='z'){
                c-=32;
            }
        }else{
            if(c>='A'&&c<='Z'){
                c+=32;
            }
        }
        printf("%c\n",c);
    }



    return 0;
}

