/*
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeollllllIIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeIIoVEEEEEEEvlIiiiiiiIi!!!iIvOEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeI!!!!!IvEEEEoiiIIllllIIIIIli!ilvEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEElIIi!!!ii!!!lEEviIlllIi!!!!!!!IoIIIilOEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOoII!!!!!!!IllI!iLoIlIiiiIIII!!!!!loIIIilLEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeevllvoIIIlIIIIloollevli!ii!!!!!!!!!ILvlIIiIoeEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELLevllIIllIlollllllllllollllIIoolIIIlIIii!lLevlIIiIlloEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEELollIIIiiIIIIIIIloIIIIIIIIIIIllllollllovoollooooeeeelIIIiiIIleEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVvolI!!iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIlllIlvvlloIiiiIlooIlllIIiiIlvEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEvooI!!!!iIIiIIIIlIIIIiIIIIIIIIIIIIIIIIli!!!IoliIol!!!!!!!!!!!iiiIllIiIlLEEEEEEEE
EEEEEEEEEEEEEEEEEELlIlli!!IIIIIIIIlvOliII!ilIIIIIIIIIIIIiIIIIii!ilolill!!!!!!!!!!!IollIooi!ILEEEEEEE
EEEEEEEEEEEEEEEEEoIloIIIIIIloIIIooIivvIIIIIIIIIllIIIlIIIIIIIIIIIIIIooIlo!!!!!!!ioeolIIilLvl!oEEEEEEE
EEEEEEEEEEEEEEEEeiIvIIIIIIleliloi!!!!IooolIIIIIIlolIlooolIIIIIIIIIIIveIleI!!!!IeeoIIIIIioEVlIVEEEEEE
EEEEEEEEEEEEEEELIIeIIIIIIlLeill!!!!!!!illovlIIIIIIovlIIoevoIIIIIIIIIIevioEI!!iOVevIIIIIioEEevEEEEEEE
EEEEEEEEEEEEEEEviLLiIIIIIvOvloiiiIIi!!!!iiovllllllllvvoIIovvlIIIIIIIioLolLVlIeEEVeIIIIiIeEVVEEEEEEEE
EEEEEEEEEEEEEEEvoEvIIIIIlLIIeI!!!iIIIi!!!!!iIiiiIlllIlooIIloeoiIIIIIioLvovEEVEEEEOliIiivEEEEEEEEEEEE
EEEEEEEEEEEEEEELLVVoiIIIvv!!iiIlllIIi!!!!!!!!!!!!!IoeveLLvliIvoIIIIIioevvOEEEEEEEeliilvEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEVVEoiiIol!IvLellvOVVLi!!!!!!!!!iLeLo!ieVVVOelllIIIilLvveEEEEEEEEviIoVEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEOEEvliillVvlLIivVOOVI!!!!!!!!!ii!OOoeVLvVeeLIlIIloooeeEEEEEEEEOeoEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEoooooi!LOveeoLL!!!!!!!!!!!!!ILeoolvLI!illIooIoIvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEVovLI!!!IlIIll!!!!!!!!!!!!!!!!iIIlIi!iooollllIlvEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEVlIeo!iiiIIIi!!!!!!!i!!!!!!!!!!iIiiIIIovIlllllIoEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEOlvELliIIIIII!!!!!iii!!!ii!!!!!iIIIIiilllolollEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEELOELeoIi!!!!!!!!!!Iii!iIi!!!!!!!!!iiIvovOvlIIloEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEviIovviiiii!!!!!!!!!!!!!!!!!iiIlEEEOLELlioeeLEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEOoiieVVEEOoIllovelllllolLVVVEEEEEEEEEEEeiIEEOEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEvIleVVEEEEVLOVOvvevvovOVOLOLLVEEEEEEELeeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEveEEEEVOLLLeevLLLeeeLOLLOLLLLOEEEEEVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLLeveeeLevveLLLLOLLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLLLLeveOvOOveeLLLOEVOLLOOLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOOLLOOOLOOOLOOLLLOEEVOLLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOOLLLLevOLLLLLLLLOOeeLLLLOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLOLLLLLLLOOLLLLLLLLOvlvvvOEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOOLLLLOLvLVLLLLLLLLLOoioLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELvOOLLLLLLLLOVOLLLLLLLLLOvIeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeolvevOLLLLOOOOLOOOLLOOLLeoLevEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvIlLlvoovIvvleelevoOvlLvlLvoveolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvlevoOeoeolOeleelLLovLooOeIvolEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVelvolovloLvleeIveIIollleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOIiIIIIivEEEEVliIiii!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEv!!!!!!leEEEEe!!!!!!oEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEoiiii!oLEEEEOoIlllleEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLOLLOOEEEEEEOOOOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVLLOLOEEEEEEEOLLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOLLLVEEEEEEEVOLLOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOLOVEEEEEEEEVOOVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVOVEEEEEEEEEEVVVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                賢い　可愛い　エリチカ Хорошо  保佑无BUG
                μ's は　大好き
                みんな　は　大好き
                LOVELIVE!  ラブライブ
*/


#include <cstdio>
#include <cstring>
using namespace std;
typedef long long LL;

LL f[1005];

void init(){
        memset(f,sizeof(f),0);
        f[1]=f[0]=1;
}
LL F(int n){
        return f[n]!=0?f[n]:(F(n-1)*2%1000007);
}
int main(){
        init();
        int n;
        while((scanf("%d",&n))!=EOF){
                printf("%lld\n",F(n));
        }
        return 0;
}
